# Generated by Django 5.0.2 on 2024-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='con',
            field=models.CharField(choices=[('se', 'Sedan'), ('hat', 'hatch')], default='', max_length=40),
        ),
    ]
